version: "3.9"
services:
  db:
    image: postgres:15
    container_name: nest-manager-db
    restart: always
    environment:
      POSTGRES_USER: yosip
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nest_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
